### ISSUE TITLE
Can't add an article

### ISSUE THREAD

**Issue by finn-stainton** [CISE-S1-2020-Team16/SEER#13]
When trying to add an article. It doesn't respond and is like it is frozen.

**Comment by finn-stainton** [comment]
Also if you call the api https://seer-staging.heroku.com/api/articles
It responds with
![image](https://user-images.githubusercontent.com/10103221/84487991-ab592d00-acf3-11ea-9083-59ed0657e3da.png)

**Comment by Aizeru** [comment]
![image](https://user-images.githubusercontent.com/53991455/84491409-9b901780-acf8-11ea-9218-a7c1c6b71e52.png)

when checking the api i get all articles currently there and when adding articles they are added normally from my end

**Comment by finn-stainton** [comment]
The staging app client had an incorrect api URL
